In [2]:
#importing pandas library,hear pd is a sub library of pandas
import pandas as pd 
import numpy as np

In [3]:
df=pd.read_csv("/home/omraj/Downloads/daexam.txt")#reading the data

In [4]:
temp_df=df#storing the data in temp variable 

In [5]:
del df['Id']#deleting the ID column
del df['Unnamed: 0']#deleting the Unnamed column
df.head(4)#dataframe checking

Ht     Wt  Engg/Science  Keralite/NK Daily Exercise  \
0  7.27  94.36             1            1              1   
1  7.32  86.34             1            0              0   
2  7.79  35.89             0            0              0   
3  7.58  91.58             1            1              1   

   % marks for qualifying  12maths  12Science  Degreemajor  Hostel/Dayscholar  \
0                   69.19    60.38      58.76        69.78                  1   
1                   74.45    52.45      49.90        66.45                  1   
2                   68.79    47.48      46.96        63.13                  0   
3                   65.25    66.31      67.62        66.78                  1   

  Marks DA Av hrs for study/day  
0       62                    4  
1       55                    3  
2       52                    3  
3     1.69                    4

In [6]:
#hear i am checking null value in data frame
df.isnull().sum()

Ht                        0
Wt                        0
Engg/Science              0
Keralite/NK               0
Daily Exercise            0
% marks for qualifying    0
12maths                   0
12Science                 0
Degreemajor               0
Hostel/Dayscholar         0
Marks DA                  0
Av hrs for study/day      0
dtype: int64

# clean Av hrs per day col for int values only 

In [7]:
#hear i am cheacking the unique value of thease column
df["Av hrs for study/day"].unique()

array(['4', '3', '0', '2', '6', '5', '1', '-2', 'mobile', 'gen', '46',
       '-1'], dtype=object)

In [8]:
#making the list of Av hrs for study/day for loop
study = list(df['Av hrs for study/day'])

In [9]:
#Hear i am assigning the nan value on the place of noisy data
studytime=[]
for i in study:
    if(i==( 'gen')or i==('mobile') or i==('46')):
        studytime.append(np.nan)
    else:
        if(int(i)<0):
            studytime.append(-1*(int(i)))
        else:
            studytime.append(int(i))
    

In [10]:
#Hear i am making arry for reeplacing nan value to mean value of those column
t = studytime
study_time = np.array(t)
df['Av hrs for study/day']=study_time

In [11]:
#hear i am filling the mean value 
df['Av hrs for study/day'].fillna((df['Av hrs for study/day'].mean()),inplace=True)

# clean Daily exercise column with deleting noise data row

In [12]:
#checking the unique value of these column
df["Daily Exercise"].unique()

array(['1', '0', 'q]'], dtype=object)

In [13]:
#deleting the noisy row
rem = df[df['Daily Exercise']=='q]']
df = df.drop(rem.index,axis=0)

# clean Marks DA column

In [14]:
#Hear i am checking unique value of these column
df['Marks DA'].unique()

array(['62', '55', '52', '1.69', '25', '11', '65', '83', '73', '47', '80',
       '69', '84', '71', '21', '85', '18', '37', '43', '28', '33', '34',
       '48', '87', '54', '60', '38', '58', '32', '45', '88', '53', '9',
       '64', '19', '7', '8', '68', '31', '78', '72', '10', '56', '5',
       '81', '40', '30', '82', '39', '76', '16', '77', '61', '70', '35',
       '36', '41', '29', '50', '6', '46', '90', '23', '155p', '26', '14'],
      dtype=object)

In [15]:
#making list of those column for assigning the nan value using loop
damrk=list(df['Marks DA'])

In [16]:
#hear assigning the nan value on noisy data
marksda=[]
for i in damrk:
    if(i=='1.69')or(i=='155p'):
        marksda.append(np.nan)
    else:
        marksda.append(int(i))


In [17]:
#making arry for reeplacing nan value to mean value of those column
t = marksda
marks_da = np.array(t)
df['Marks DA']=marks_da

In [18]:
#filling the mean value 
df['Marks DA'].fillna((df['Marks DA'].mean()),inplace=True)

# for Hostel/Dayscholar

In [19]:
#checking the unique value of these column
df["Hostel/Dayscholar"].unique()

array([ 1,  0, 12])

In [20]:
#making list of those column for loop
Hd=list(df['Hostel/Dayscholar'])

In [21]:
#hear assigning the nan value on noisy data
Hod=[]
for i in Hd:
    if(t==12):
        Hod.append(np.nan)
    else:
        Hod.append(i)

In [22]:
#making arry for reeplacing nan value to mean value of those column
t = Hod
H_d = np.array(t)
df['Hostel/Dayscholar']=H_d

In [23]:
#filling the mean value 
df['Hostel/Dayscholar'].fillna((df['Hostel/Dayscholar'].mean()),inplace=True)

In [24]:
df.head(5)#filnaly checking the cleaned data 

Ht     Wt  Engg/Science  Keralite/NK Daily Exercise  \
0  7.27  94.36             1            1              1   
1  7.32  86.34             1            0              0   
2  7.79  35.89             0            0              0   
3  7.58  91.58             1            1              1   
4  6.52  38.17             0            1              0   

   % marks for qualifying  12maths  12Science  Degreemajor  Hostel/Dayscholar  \
0                   69.19    60.38      58.76        69.78                  1   
1                   74.45    52.45      49.90        66.45                  1   
2                   68.79    47.48      46.96        63.13                  0   
3                   65.25    66.31      67.62        66.78                  1   
4                   65.51    22.75      24.50        47.13                  0   

    Marks DA  Av hrs for study/day  
0  62.000000                   4.0  
1  55.000000                   3.0  
2  52.000000                   3.0  
3  48.092784                   4.0  
4  25.000000                   0.0

# M L classification Algoritham (1)RandomForest


Hear i am going to classify studet are  doing excercise or not,And i am using the random forest classification algoritham./Random forest is a supervised learning algoritham
/Random forest algorithm or the random forest classifier can use for both classification and the regression task.
/Random forest classifier will handle the missing values.
/Random forest classifier for categorical values also.
/The overfitting problem will never come when we use the random forest algorithm in any classification problem.

In [25]:
#importing library
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [26]:
y=np.array(df['Daily Exercise'].astype('int'))

x=np.array(df.drop('Daily Exercise',axis=1))
y

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0])

In [26]:
train_X, test_X,train_y, test_y = train_test_split(x,y,test_size = 0.3,random_state = 4 )   

In [27]:
len( train_y)

69

In [28]:
len( test_y )

30

In [29]:
radm_clf = RandomForestClassifier()
radm_clf.fit( train_X, train_y )

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [30]:
radm_test_pred = pd.DataFrame( { 'actual':  test_y,'predicted': radm_clf.predict( test_X) } )                          

In [31]:
accuracy_score( radm_test_pred.actual, radm_test_pred.predicted )

0.9666666666666667

In [32]:
print(confusion_matrix(test_y,radm_clf.predict(test_X)))

[[19  0]
 [ 1 10]]


# (2)Logistic Regression

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report

/home/omraj/.local/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [34]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = .3, random_state=25)

In [35]:
LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [36]:
y_pred = LogReg.predict(X_test)

In [37]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0])

In [38]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.85      1.00      0.92        17
          1       1.00      0.77      0.87        13

avg / total       0.91      0.90      0.90        30

